### ISSUE TITLE
Rec room can be played on android

### ISSUE THREAD

**Issue by NoenD455** [readyready15728/awesome-programming-games#14]
https://g.co/kgs/vGjLAEP

**Comment by readyready15728** [comment]
How does this game hone programming skills specifically?

**Comment by NoenD455** [comment]
what does this all mean

**Comment by readyready15728** [comment]
How is Rec Room a programming game?

**Comment by NoenD455** [comment]
Idk what I meant by rec room but you should add sand:box and roody2d because they feature logic gates

**Comment by readyready15728** [comment]
Can you give me links so I can investigate a bit further?

**Comment by NoenD455** [comment]
Look them up

**Comment by readyready15728** [comment]
Roody:2d isn't so hard but with the other one it's a bit more ambiguous doing the searches

**Comment by NoenD455** [comment]
Search it up on steam

**Comment by readyready15728** [comment]
OK, so I looked and here's one of the cases I'm on the fence about:
https://store.steampowered.com/app/2179380/Sandbox/
I think including it might cast the net a little too wide, but I'm still not sure...

**Comment by NoenD455** [comment]
It has logic gates ROMs busses and leds and also all the main game stuff
but we don't care

**Comment by readyready15728** [comment]
No need for sarcasm; it's just Sunday and I want to rest a bit. I think I will probably include this game based on your input and what I've read.

**Comment by readyready15728** [comment]
Done
